from groq import Groq

from config import GROQ_API_KEY

client = Groq(api_key=GROQ_API_KEY)


SYSTEM_PROMPT = """
You are an AI content attribution assistant.

Determine whether the following text appears to be written by a human or generated by AI.

Respond using ONLY this JSON format:

{
  "classification":"likely_human",
  "score":0.83
}

or

{
  "classification":"likely_ai",
  "score":0.91
}

Rules:
-score must be between 0 and 1.
-higher score means higher confidence.
-no explanations.
-output valid JSON only.
"""


def llm_signal(text):

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        temperature=0,
        messages=[
            {
                "role": "system",
                "content": SYSTEM_PROMPT
            },
            {
                "role": "user",
                "content": text
            }
        ]
    )

    import json

    result = json.loads(response.choices[0].message.content)

    return result